### PR TITLE
feat: group log output

### PR DESCRIPTION
**Pull request by villelahdenvuo**
I added grouping to the log output to make it easier to go through the output.

### CODE REVIEW

**Review by jonabc — APPROVED** [review]
looks great, thanks for splitting this separately from the style changes 🙇

**Comment by jonabc** [comment]
oh interesting!  looks like the "Run licensed in test" action doesn't work properly with forks.  I'll take a look separately, I don't think the change in this PR is impactful towards those failures.

Thanks again for the update 🙇

**Comment by villelahdenvuo** [comment]
@jonabc Hey, could you release a patch version for this as the output is pretty annoying currently? 😄

**Comment by jonabc** [comment]
oh, yeah sorry for the delay

**Pull request merged**
